# Generated by Django 3.0.1 on 2020-03-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app13', '0002_studentmodel_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='password',
        ),
    ]
