# Generated by Django 3.0.1 on 2020-03-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app13', '0004_remove_studentmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='username',
            field=models.CharField(default=False, max_length=30, unique=True),
        ),
    ]
